// twinkleoptions.js: personal Twinkle preferences file
//
// NOTE: The easiest way to change your Twinkle preferences is by using the
// Twinkle preferences panel, at [[Wikipedia:Twinkle/Preferences]].
//
// This file is AUTOMATICALLY GENERATED.  Any changes you make (aside from
// changing the configuration parameters in a valid-JavaScript way) will be
// overwritten the next time you click "save" in the Twinkle preferences
// panel.  If modifying this file, make sure to use correct JavaScript.
// <nowiki>

window.Twinkle.prefs = {
  "twinkle": {
    "blankTalkpageOnIndefBlock": true,
    "prodLogPageName": "",
    "autoMenuAfterRollback": true,
    "openTalkPage": [
      "norm",
      "vand"
    ],
    "speedySelectionStyle": "radioClick",
    "watchSpeedyPages": [
      "g1",
      "g2",
      "g3",
      "g4",
      "g5",
      "g6",
      "g7",
      "g8",
      "g10",
      "g11",
      "g12",
      "g13",
      "g14",
      "a1",
      "a3",
      "a7",
      "a9",
      "a10",
      "a11",
      "u1",
      "u2",
      "u3",
      "u5",
      "f3",
      "f7",
      "f9",
      "t2",
      "r2",
      "r3",
      "r4",
      "p1",
      "p2"
    ],
    "notifyUserOnSpeedyDeletionNomination": [
      "db",
      "g1",
      "g2",
      "g3",
      "g4",
      "g6",
      "g10",
      "g11",
      "g12",
      "g13",
      "g14",
      "a1",
      "a2",
      "a3",
      "a5",
      "a7",
      "a9",
      "a10",
      "a11",
      "u3",
      "u5",
      "f1",
      "f2",
      "f3",
      "f7",
      "f9",
      "f10",
      "c1",
      "t2",
      "t3",
      "r2",
      "r3",
      "r4",
      "p1",
      "p2"
    ],
    "welcomeUserOnSpeedyDeletionNotification": [
      "db",
      "g1",
      "g2",
      "g3",
      "g4",
      "g6",
      "g10",
      "g11",
      "g12",
      "g13",
      "g14",
      "a1",
      "a2",
      "a3",
      "a5",
      "a7",
      "a9",
      "a10",
      "a11",
      "u3",
      "u5",
      "f1",
      "f2",
      "f3",
      "f7",
      "f9",
      "f10",
      "c1",
      "t2",
      "t3",
      "r2",
      "r3",
      "r4",
      "p1",
      "p2"
    ],
    "warnUserOnSpeedyDelete": [
      "db",
      "g1",
      "g2",
      "g3",
      "g4",
      "g6",
      "g10",
      "g11",
      "g12",
      "g13",
      "g14",
      "a1",
      "a2",
      "a3",
      "a5",
      "a7",
      "a9",
      "a10",
      "a11",
      "u3",
      "u5",
      "f1",
      "f2",
      "f3",
      "f7",
      "f9",
      "f10",
      "c1",
      "t2",
      "t3",
      "r3",
      "r4",
      "p1",
      "p2"
    ],
    "promptForSpeedyDeletionSummary": [
      "db",
      "g4",
      "g6",
      "a1",
      "a2",
      "a3",
      "a5",
      "a7",
      "a9",
      "a10",
      "a11",
      "f2",
      "f4",
      "f7",
      "f8",
      "f10",
      "t2",
      "t3",
      "p1",
      "p2"
    ],
    "openUserTalkPageOnSpeedyDelete": [],
    "speedyWindowWidth": 675,
    "speedyWindowHeight": 650,
    "speedyLogPageName": "",
    "noLogOnSpeedyNomination": [],
    "unlinkNamespaces": [
      "0",
      "4",
      "6",
      "10",
      "100"
    ],
    "customWarningList": [
      {
        "value": "uw-ablock",
        "label": "Your IP address has been blocked from editing."
      },
      {
        "value": "uw-voablock",
        "label": "You have been indefinitely blocked from editing because your account is being used [[WP:VOA|only for vandalism]]."
      },
      {
        "value": "uw-block",
        "label": "You have been blocked from editing."
      },
      {
        "value": "uw-blocknotalk",
        "label": "You have been blocked from editing and your user talk page has been disabled."
      }
    ],
    "xfdWatchPage": "yes",
    "xfdWatchDiscussion": "yes",
    "xfdWatchUser": "yes",
    "markXfdPagesAsPatrolled": false,
    "speedyPromptOnG7": true
  },
  "friendly": {
    "customTagList": [
      {
        "value": "User:Amorymeltzer/testtag",
        "label": "Test tag don't use"
      }
    ],
    "customFileTagList": [
      {
        "value": "User:Amorymeltzer/testtag",
        "label": "test tag do not use"
      }
    ],
    "customRedirectTagList": [
      {
        "value": "User:Amorymeltzer/testtag",
        "label": "test tag don't use"
      }
    ],
    "markTalkbackAsMinor": false,
    "talkbackHeading": "Talkback from [[User:Amorymeltzer|Amorymeltzer]]",
    "mailHeading": "Mail from Amorymeltzer",
    "customWelcomeList": [
      {
        "value": "User:Fluffernutter/c",
        "label": "OS"
      }
    ],
    "customWelcomeSignature": false
  }
};

// </nowiki>
// End of twinkleoptions.js