requires 'JSON::MaybeXS';
requires 'Log::Log4perl';
requires 'Git::Repository';
requires 'MediaWiki::API';
requires 'File::Slurper';

on 'test' => sub {
  requires 'Test::Fatal';
  requires 'Test::Perl::Critic';
  requires 'Test::Pod';
  requires 'Test::Pod::Coverage';
};
