name: crathighlighter-pr

on:
  push:
    branches-ignore:
      - main
    paths:
      - crathighlighter/**

jobs:
  build:
    runs-on: macos-latest

    name: Perl macOS

    steps:
      - uses: actions/checkout@v6

      - name: Set up Perl
        run: brew install perl

      - name: perl -V
        run: perl -V

      - name: Install Dependencies
        uses: perl-actions/install-with-cpm@v2
        with:
          sudo: false
          cpanfile: "./crathighlighter/cpanfile"

      - name: Run tests
        working-directory: ./crathighlighter
        run: prove -l
