name: wikispecies-pr

on:
  push:
    branches-ignore:
      - main
    paths:
      - wikispecies/**

jobs:
  build:
    runs-on: macos-latest

    name: Perl macOS

    steps:
      - uses: actions/checkout@v3

      - name: Set up Perl
        run: brew install perl

      - name: perl -V
        run: perl -V

      - name: Run tests
        working-directory: ./wikispecies
        run: prove -l
