name: wikispecies-release

on:
  push:
    branches:
      - main
    paths:
      - wikispecies/**

jobs:
  build:
    runs-on: macos-latest

    name: Perl macOS

    steps:
      - uses: actions/checkout@v3

      - name: Set up Perl
        run: brew install perl

      - name: perl -V
        run: perl -V

      - name: Run tests
        env:
          RELEASE_TESTING: 1
        working-directory: ./wikispecies
        run: prove -l
